# Generated by Django 3.2.3 on 2021-06-08 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('accounts', '0002_auto_20210609_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
